### ISSUE TITLE
vs2019/2022 extension

### ISSUE THREAD

**Issue by Yzhao102** [shader-slang/slang-vscode-extension#2]
Hi

I'm working on falcor in Vs2019, I'm wondering is there slang extension for vs2022/2019/

Thanks
Y

**Comment by csyonghe** [comment]
Thanks for your request! We haven't created such an extension for Visual Studio yet. Right now we don't have a timeline to support Visual Studio. However, since Visual Studio supports the same language server protocol, we can hopefully reuse the same language server to create the Visual Studio extension.

We will keep you posted once we get to work on Visual Studio support.

**Comment by csyonghe** [comment]
Closing this issue now since we don't have the resources to develop a VS extension at this moment.
